# Site settings
title: Madrina
email: contact@madrinaband.com
url: https://madrinaband.com
description: "Madrina is an alternative band from Miami, Florida."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Madrina


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/madrinaband
  - title: facebook
    url:
  - title: soundcloud
    url: http://soundcloud.com/madrinaband

# Build settings
markdown: kramdown
permalink: pretty

gems:
- soundcloud_sound
